### ISSUE TITLE
i cant find a package

### ISSUE THREAD

**Issue by mbmamin1996** [moberweger/deep-prior#13]
cameradevice.py", line 30, in <module>
    import lib_dscapture as dsc
ModuleNotFoundError: No module named 'lib_dscapture'
how i can install the lib_dscapture ???

**Comment by moberweger** [comment]
You need to compile this library first: go to src/util run `cmake . `, and then `make` to build this library. Notice, that we already have a newer version of this software: [DeepPrior++](https://github.com/moberweger/deep-prior-pp)
