### ISSUE TITLE
problem with roslaunch 

### ISSUE THREAD

**Issue by mbmamin1996** [moberweger/deep-prior#14]
when i run a node with roslaunch then 
ERROR: cannot launch node of type [softkinetic_camera/softkinetic_bringup_node]: softkinetic_camera
ROS path [0]=/opt/ros/indigo/share/ros
ROS path [1]=/opt/ros/indigo/share
ROS path [2]=/opt/ros/indigo/stacks
ERROR: cannot launch node of type [softkinetic_camera/softkinetic_bringup_node]: softkinetic_camera
ROS path [0]=/opt/ros/indigo/share/ros
ROS path [1]=/opt/ros/indigo/share
ROS path [2]=/opt/ros/indigo/stacks
  

please help me to solve it

**Comment by moberweger** [comment]
This error seems related to ros. Please check their corresponding forum or
github page.

aaam <notifications@github.com> schrieb am Do., 5. Juli 2018 7:45 vorm.:

**Comment by mbmamin1996** [comment]
thanks a lot
