### ISSUE TITLE
IOError: [Errno 2] No such file or directory: './NYU_network_prior.pkl'

### ISSUE THREAD

**Issue by mbmamin1996** [moberweger/deep-prior#17]
i make the test_1 and test_2 folder and when i run the code i have this . help me please 
ali@ali-X555LD:~/Desktop/code/deep-prior-master/src$ sudo python test_realtimepipeline.py 
Loading cache data from ./cache//NYUImporter_test_1_False_False_cache.pkl
/home/ali/Desktop/code/deep-prior-master/src/net/convpoollayer.py:301: UserWarning: DEPRECATION: the 'ds' parameter is not going to exist anymore as it is going to be replaced by the parameter 'ws'.
  pooled_out = pool_2d(input=conv_out, ds=poolsize, ignore_border=True)
Traceback (most recent call last):
  File "test_realtimepipeline.py", line 63, in <module>
    poseNet.load("./NYU_network_prior.pkl")
  File "/home/ali/Desktop/code/deep-prior-master/src/net/netbase.py", line 414, in load
    handle = opener(filename, 'rb')
IOError: [Errno 2] No such file or directory: './NYU_network_prior.pkl'

**Comment by moberweger** [comment]
Looks good so far. For the nyu_network_prior.pkl you should download the
pretrained models and specify the path to point to these models.

aaam <notifications@github.com> schrieb am Mi., 18. Juli 2018 10:01 nachm.:

**Comment by mbmamin1996** [comment]
thanks alot 
after this i run the code then i have this  
help me please 
TypeError: Cannot convert Type TensorType(float32, 4D) (of Variable Subtensor{int64:int64:}.0) into Type TensorType(float64, 4D). You can try to manually convert Subtensor{int64:int64:}.0 into a TensorType(float64, 4D)

**Comment by moberweger** [comment]
Try running the code with `THEANO_FLAGS=device=gpu,floatX=float32`
