### ISSUE TITLE
use the camera 

### ISSUE THREAD

**Issue by mbmamin1996** [moberweger/deep-prior#18]
Which file must be run to use the camera And do code for a my hand ??

**Comment by mbmamin1996** [comment]
To use a camera and detect my hand ??

**Comment by moberweger** [comment]
To do that, use the file test_realtimepipeline.py

**Comment by mbmamin1996** [comment]
Ok I do that but I have just a lot of frame of another hand
And never ask me to connect camera.

**Comment by mbmamin1996** [comment]
Please help me

**Comment by moberweger** [comment]
So you want to run files or "live" with a camera? In both cases use test_realtimepipeline.py . When running single frames, add them to the list in test_realtimepipeline.py#L83
When running with a camera, uncomment the lines starting at test_realtimepipeline.py#L87 , but this only works with Creative Senz3D camera.
