### ISSUE TITLE
Input and output size of the CNN layers

### ISSUE THREAD

**Issue by shimiaoli** [moberweger/deep-prior#4]
Hi @moberweger ,
I am checking the input and output dimension of each layer in the pose estimation cnn (PoseNet).
Here is the list of layer input and output based on my understanding of the code. (I separate conv layer and pooling layer here for easy understanding)
layer 1: convolutional_layer input 128 * 128 * 1 output 124 * 124 * 8,  5 * 5conv , 8 feature maps; (padding is valid)
layer 2: max_pooling_layer with relu,  input 124 * 124 * 8,  output 31 * 31 * 8,  4 * 4pooling (stride = 1)
layer 3: convolutional_layer,  input 31 * 31 * 8  output 27 * 27  * 8,  5 * 5 conv, 8 feature maps (padding is valid)
layer 4: max_pooling_layer with relu  input 27 * 27 * 8 output 13*13*8,    2 * 2pooling  (strid e = 1)
... 
It seems in the input of layer 4 has odd number of width and height, which can not be divided by the poolsize 2.  so the last row or column of the input was just dropped ? or do I miss anything here ?

Many thanks.

**Comment by moberweger** [comment]
Hi @shimiaoli 

This is due to the Theano [pool operator](http://deeplearning.net/software/theano/library/tensor/signal/pool.html). It ignores the borders and simply drops the part that does not fit in the max pool window.
