### ISSUE TITLE
Loading depth map of ICVL data

### ISSUE THREAD

**Issue by shimiaoli** [moberweger/deep-prior#6]
Hi, @moberweger 

It seems in the code importer.py , you use this function to load depth image in ICVL dataset.

def loadDepthMap(self,filename):
        """
        Read a depth-map
        :param filename: file name to load
        :return: image data of depth image
        """

        img = Image.open(filename)  # open image
        assert len(img.getbands()) == 1  # ensure depth image
        imgdata = np.asarray(img, np.float32)

        return imgdata

However, ICVL depth images are png images with 3 channels. I don't understand how the above function can load the depth image with float32 numbers as output. I suppose the loading method here should be the same as in NYUimporter:

def loadDepthMap(self,filename):
        """
        Read a depth-map
        :param filename: file name to load
        :return: image data of depth image
        """

        img = Image.open(filename)
        # top 8 bits of depth are packed into green channel and lower 8 bits into blue
        assert len(img.getbands()) == 3
        r, g, b = img.split()
        r = np.asarray(r, np.int32)
        g = np.asarray(g, np.int32)
        b = np.asarray(b, np.int32)
        dpt = np.bitwise_or(np.left_shift(g, 8), b)
        imgdata = np.asarray(dpt, np.float32)

        return imgdata

But the code actually works well with ICVL data.  Could you help to explain ?

Thank you.

**Comment by shimiaoli** [comment]
I just examined the three channels of png image in ICVL data. It seems all the three channels have the same content.  background has value 125, face area has value 2, hand area has value 1. How should we interpret and load this depth image ? Thanks a lot !

**Comment by moberweger** [comment]
Hi @shimiaoli 
Loading the depth images depends on the encoding used to save the original depth images. The NYU data uses a special encoding, which split the depth range to different colour channels. Each channel encodes some bits of the original depth value. The ICVL data is a standard png image with uint16 encoding. The background and face area with values that you observed might be an artifact of this encoding. I use the PIL library to load the images, which handles all these encoding well.

**Comment by shimiaoli** [comment]
Hi , @moberweger 
Thank you for the explanation.
I didnot load the data as uint16. After loading it correctly, face area has value 658, hand area has value 367, background 32001. I guess the unit here can be mm.
