### ISSUE TITLE
test_1 and test_2 in NYU dataset

### ISSUE THREAD

**Issue by hassony2** [moberweger/deep-prior#8]
Hi,

Thank you very much for this code. I found your paper very interesting and I am trying to reproduce the basic training step.
 
I was trying to retrain the network using `python main_nyu_posereg_embedding.py` and I ran into the following issue : it tries to load the test_1 and test_2 sequences, and the folders data/test_1 and data/test_2 do not exits. 
When I downloaded the NYU dataset I have only a _train_ and a _test_ dataset, did you make a custom split, or am I missing something in the initial configuation steps ?

Best,

Yana

**Comment by moberweger** [comment]
Hi @hassony2 
The test_1 and test_2 sets are obtained by separating the NYU test set into the two different subjects. test_1 contains images 1-2440, and test_2 the rest. This allows for adjusting the hand size for each subject.

**Comment by hellojialee** [comment]
HI~
What's the difference of test_1 and test_2?  What's the reason for adjusting the hand size for each subject?
Thank you

**Comment by moberweger** [comment]
The reason for adjusting the hand size is, that the crop of the hand (CNN needs fixed size input) depends on the size of the users hand. For NYU, the two hands have very different sizes, and adjusting the crop to the physical hand size makes it easier for the CNN to generalize to different users (ie hand sizes).

**Comment by hellojialee** [comment]
Yes, I agree. But this trick can't be applied in practice considering that we don't know the difference of a person's hand size.

**Comment by moberweger** [comment]
There is a function included that estimates the hand size in practice, see `util/handdetector.py:detect`. This can be invoked by the realtime pipeline by pressing `i`.

**Comment by WeihongM** [comment]
a problem, you mean I randomly choose 1-2440 pngs into test1, and others into test2?  @moberweger

**Comment by WeihongM** [comment]
@moberweger  because some file is depth, rgb and synthdepth png, not sure how to divide?

**Comment by moberweger** [comment]
@WeihongM 
The NYU test set consists of 2 different users. The first 2440 frames are for 'test_1', the remaining frames are for 'test_2', so you simply have to split them into two folders. Split all files (depth, rgb, synthdepth).

Anyway, this code is outdated, so please use https://github.com/moberweger/deep-prior-pp

**Comment by weiguochow** [comment]
Hi,
Thank you for your code. I have split the dataset into test_1 and test_2. but there is an error 

  File "main_nyu_com_refine.py", line 56, in <module>
    Seq2_1 = di.loadSequence('test_1',docom=True)
  File "/home/alex/PhD/DeepPrior/deep-prior-master/src/data/importers.py", line 553, in loadSequence
    mat = scipy.io.loadmat(trainlabels)
  File "/home/alex/anaconda2/envs/tensorflow/lib/python2.7/site-packages/scipy/io/matlab/mio.py", line 141, in loadmat
    MR, file_opened = mat_reader_factory(file_name, appendmat, **kwargs)
  File "/home/alex/anaconda2/envs/tensorflow/lib/python2.7/site-packages/scipy/io/matlab/mio.py", line 64, in mat_reader_factory
    byte_stream, file_opened = _open_file(file_name, appendmat)
TypeError: 'NoneType' object is not iterable

regards
weiguo

**Comment by moberweger** [comment]
@weiguochow 
Did you copy the annotation file (*.mat) as well? The error looks like the file is missing.
Also, this code is outdated, so please use https://github.com/moberweger/deep-prior-pp

**Comment by WeihongM** [comment]
@moberweger  sorry，Thank you for your code, 
now I have split the test file into test_1 and test_2. But I am not sure whether I need to extract the "test_predictions.mat"  file to get correspond row of my extracted test_1 and test_2. 
or I only need to copy the whole "test_predictions.mat" into test_1 and test_2, and not need to change the .mat file.
Hope for your answer sooner !

**Comment by moberweger** [comment]
@WeihongM 
Yes, that is the way to go. You can simply copy the whole predictions.mat file into both folders without changing the file itself.

**Comment by WeihongM** [comment]
@moberweger 
Thanks for your reply so quickly .
now I met another problem.  I have split the test file into test_1 and test_2 ， and the test_predictions.mat to each folder.  However, I find your code  
`        # Load the dataset
        objdir = '{}/{}/'.format(self.basepath, seqName)
        trainlabels = '{}/{}/joint_data.mat'.format(self.basepath, seqName)

        mat = scipy.io.loadmat(trainlabels)
        names = mat['joint_names'][0]
        joints3D = mat['joint_xyz'][0]
        joints2D = mat['joint_uvd'][0]`
in deep-prior-pp/data/importers.py  row 958.
you named the  *.mat file as joint_data.mat, so I changed the .mat file name, and the next I donot know how to change the key value, because the key value in *.mat file is ['pred_joint_uvconf', '__version__', '__header__', 'conv_joint_names', '__globals__']
rather than 'joint_names', 'joint_xyz', 'joint_uvd'. 
sorry to trouble you, thanks.

**Comment by WeihongM** [comment]
@moberweger  sorry, it seems that I have download the wrong dataset, rather than hand pose v2.0,
